### ISSUE TITLE
Problem with TerminalBlock_WAGO-236* ?

### ISSUE THREAD

**Issue by bobc** [KiCad/TerminalBlock_WAGO.pretty#2]
These footprints seem to be a little off. The datasheet at https://eshop.wago.com/JPBC/0_5StartPage.jsp?zone=6 suggests that the pin spacing is nominally 5mm. However the description says "Set to metric or inch pin spacing by compressing PCB terminal strips or pulling them apart" which is impossible to capture in a single footprint. 

The actual footprint has 5.08 mm spacing vertically, then alternates 5.08mm and 4.953 horizontally, which seems weird. Is that intentional?

The vertical error doesn't matter, but over several pins the horizontal error will accumulate. It seems there should be separate footprints for a nominal 5mm, and 5.08mm pitch.

Were these generated by script? I searched but didn't find one.

**Comment by jkriege2** [comment]
I'm planning to redo all the terminal block within the next few weeks ... for the RND series I already wrote a new script that generates the footprints (45° blocks are still missing though) ... but I wanted to use that for all blocks ... see: https://github.com/pointhi/kicad-footprint-generator/pull/68

JAN

**Comment by SchrodingersGat** [comment]
Jan if you are going to rewrite the terminal blocks please ensure you use the naming scheme I have used here - https://github.com/KiCad/kicad-footprints/pull/7

**Comment by jkriege2** [comment]
Hi @SchrodingersGat!

Shouldn't the naming follow the new KLC? I would have changed it a bit to:
- `TerminalBlock_WAGO-236-10Pin_P5.00mm` instead of `TerminalBlock_WAGO-236_2Stift_RM5mm_10pol` (i.e. change location of pol, remove the german 2Stift which seems not required to me and using P for Pitch instead of RM for Rastermaß)
- `TerminalBlock_WAGO-804_3Pin_P7.50mm` instead of `TerminalBlock_WAGO-804_RM7.5mm_3pol`

I also wanted to change the naming of the ones I made earlier to conform with this 
- `TerminalBlock_RND_205-00001_1Pin_P5.00mm` instead of `TerminalBlock_RND_205-00001_Pitch5.00mm` (shorten Pitch to P as that seems the decision that was done according to new KLC and add pin-count)

In both I took the liberty to add `Pin` to the pin-count to make it understandable, which a single number in the name would be NOT.

... OK? If not, we should fix the naming scheme NOW! @evanshultz @poeschlr What do you think on naming?

Best,
JAN

**Comment by poeschlr** [comment]
According to KLC, `TerminalBlock_WAGO-236-10Pin_P5.00mm` should be named `TerminalBlock_WAGO_236_1x10_P5.00mm_[orientation]`

**Comment by SchrodingersGat** [comment]
As in the other PR I just commented on, you should use the `1x10_P5.00mm` format. This makes it consistent with other connectors.

**Comment by poeschlr** [comment]
Side note: Do not use straight/angled for orientation. The new KLC defines that only horizontal/vertical should be used.

**Comment by jkriege2** [comment]
I added PRs for RND and Metz as a test baloon:
- https://github.com/KiCad/kicad-footprints/pull/10
- https://github.com/KiCad/kicad-footprints/pull/11

Please review, so I can start redoing the others (but might take some time)

**Comment by SchrodingersGat** [comment]
@bobc I believe this has been addressed now? If not, please re-open this issue at the new repo - https://github.com/kicad/kicad-footprints
